"""comments

Revision ID: 206bc3288c55
Revises: df67376394e0
Create Date: 2019-06-19 11:25:53.300647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206bc3288c55'
down_revision = 'df67376394e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_option_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_option_id'], ['user_option.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
